[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firerust = "1.0.1"
serde_json = "1.0.89"
actix-web = "4"
futures = "0.3"
